
language: swift
osx_image: xcode11
env:
  global:
  - IOS_SIMULATOR='name=iPhone 11,OS=13.0'
  - IOS_SDK=iphonesimulator13.0
  - SWIFT_VERSION=5.0
  - SCHEME=RxNetwork
  - WORKSPACE=RxNetwork.xcworkspace

before_install:
  - gem install cocoapods
  - gem install xcpretty

script:
  - pod install
  - xcodebuild -version
  - xcodebuild -showsdks
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk $IOS_SDK  -destination "$IOS_SIMULATOR" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_VERSION=$SWIFT_VERSION build | xcpretty
